### ISSUE TITLE
"dotenv File not found", and "TOKEN is uncalled for"

### ISSUE THREAD

**Issue by immason29** [friscorp/erlc-bot#1]
Hey guys, it appears I am getting this issue and I am not exactly sure how to solve it, ALSO - I saw a bunch of people fork this project and put their tokens straight into the code, DON'T DO THAT because now **ANYONE CAN USE YOUR BOT TO SPAM USING YOUR BOT **TOKEN****, please never put your bots token straight into the github repo and only put it on server-side resources, this will help prevent people from getting your token easier. @friscorp

**Comment by sspccreates** [comment]
Fixed the issue, used `npm install dotenv`
